### ISSUE TITLE
Use jekyll for building pages

### ISSUE THREAD

**Issue by MartinDelille** [yaml/www.yaml.org#62]
Contributing with html code is very error prone. I would suggest to generate html with [Jekyll](https://jekyllrb.com/) which works great with [Github Pages](https://pages.github.com/).

*Jekyll* makes extensive use of *YAML* with [its configuration file](https://jekyllrb.com/docs/configuration/default/) and [its collections](https://jekyllrb.com/docs/collections/).

I'm quite experienced with it so I'll be happy to help!

**Comment by perlpunk** [comment]
I agree and that's also what @ssbarnea suggested.
The plan for the existing pages on yaml.org is to not modify them anymore, though. Except index.html of course.
The specs for the existing YAML versions are not changing anymore, and we can't also rebuild them because the link ids will change, making existing links invalid or wrong.
A new YAML version 1.3 is planned.
@ingydotnet wants all the new content to be on https://www.yaml.io/

**Comment by MartinDelille** [comment]
Awesome! The site is so cool!

**Comment by MartinDelille** [comment]
Ok last commit is 4 years ago. Looks kind of dead.

**Comment by ingydotnet** [comment]
Not dead, just stalled ;)

Expect content to begin showing up regularly in the next month or so.

**Comment by ssbarnea** [comment]
Not dead, but stalled because it requires serious work to make it easy to maintain. One month ago I started to rebuild the site using hugo but never managed to finish it.

**Comment by MartinDelille** [comment]
I really like the <https://yaml.org/> design. https://yaml.io/> design is fresh and clean but that would be cool to present this *yaml* way of presenting content (I would go even further by removing the column layout).

I never used Hugo but heard a lot of good about it. If you want some help, this could be a good playground for me to learn!
