### ISSUE TITLE
Yaml is actively harmful. This site should not exist.

### ISSUE THREAD

**Issue by duaneking** [yaml/www.yaml.org#91]
With all due respect, I understand that the title might be kind of controversial to those of you in the community who do not understand all of the issues at play, and so with the most respect possible, I'm going to try to be professional here now that I have your attention.￼

Out of respect, I will make my case bluntly:

1. Yaml requires whitespace that actively discriminates against the disabled or older engineers who may have decreased sight.

2. This requirement for non-terminal whitespace￼ To have configuration and execution context is an active issue in the communities that use it that causes problems and errors, often creating issues because even the most fully sighted and careful people will still make mistakes, because the format is so restrictive when it comes to whitespace. Due to this bad design, it's very error prone.￼

3. The jokes and comments about the YAML format being "made for humans" may not be meant to be discriminatory, but they absolutely are, Because what you're really saying is that humans should be allowed to use it, and if you're not able to because of disabilities such as vision issues, then you're not *really* human￼. This is explicit discrimination on its own.￼

4. This website perpetuates the yaml format, and by doing so, it also perpetuates the inevitable discrimination that happens when somebody wants to join a project that forced the use of yaml (k8s, others) but they are also limited by a disability such as vision loss.

It took me losing my eye as punishment for defending somebody a bully was picking on to give me a different perspective, so I understand that if you are reading this and have 2 working uninjured eyes, this may not seem like a big deal to you. 

But if you're trapped in your head because the hollow grey of blindness is all you can see, and you're isolated because of the pandemic and nobody's around to help you, then how are you supposed to join a community, build relationships, or do anything in these communities that require this if the technology itself actively creates a barrier for your contribution or use?￼

So with all due respect this file format is actively harmful and holds back the progress of humanity, it should be discarded, and I would like you to simply delete it and abandon it, to help humanity progress to using file formats that are not abilest, please￼.

**Comment by ingydotnet** [comment]
@duaneking,

The world is diverse in terms of people, ideas, beliefs, abilities and technologies. YAML is one of many projects I've contributed in an attempt to lower the barriers of communication between people and computers. Depending on who you ask, it currently falls anywhere between totally amazing and abject failure. I know where you stand.

The good news is that it is a work in progress. In less than 2 hours the Revision 1.2.2 of the YAML Specification will be released. This is a big step in our ambition to see the language progressively evolve to become more helpful to people.

Your constructive ideas for improving YAML for everyone are welcomed by the [YAML Language Development Team](https://spec.yaml.io/main/ext/team).

— @ingydotnet

PS - Both of my eyes are physically damaged.

**Comment by perlpunk** [comment]
Hi @duaneking ,

my case is not comparable to yours, but still I would like to give you my feedback on this.

People's disabilities vary a lot, and it would be easy to call many things "explicitly discriminating". I just don't find that very constructive.

Let me give you an example. I like to use `tmux` and `tmate` (a terminal multiplexer that can be used for pair programming).
The default prefix key shortcut is `ctrl-b`. Now, I was born without my right forearm. I type with my left hand and press `shift` and arrow keys with my right elbow.
`ctrl-a` is relatively easy to type for me with my left fingers, but `ctrl-b` is just too cumbersome for an often used prefix key. _(*) There is a workaround, but with exceptions, see below_

Now, I can configure my own `tmux` to use `ctrl-a`, but when I pair-program with others in `tmate` I have to use their default, `ctrl-b`, because every participant has to use the same prefix key.

I would never think of calling tmux explicitly discriminating because the authors chose `ctrl-b`, though.
Different people have different needs, and it's usually impossible to account for every need.
While I would be fine with `ctrl-a`, right-only handed people wouldn't.

Obviously a lot of people find YAML very useful, and also a lot of people find it annoying. There are even people doing both.

Everyone should try to make websites, tools, languages as accessible as possible to everyone, but also opinions on that might vary.
There might be editor tools helping with some of the problems (not assuming that you didn't try such things of course).
For example I have heard several times that people have problems if they accidentally add a tab in their YAML file.
In my editor configuration (vim), I let it show tabs and trailing spaces, so I wouldn't easily miss it.

I also hope we can get better YAML tools in the future, that e.g. could do an indent-change for better readability. While we try to improve YAML, one goal is to improve the tools for it.
We hope for constructive feedback.

(*) I use Linux, and there I can use `xmodmap` to map `ctrl-b` onto the OS key on my keyboard. That's actually pretty cool, because normally you can't map key combinations, but since ctrl-b is a keycode itself, it works. It's just that one of my laptops has a hardware problem making that mapping unusable for me.
